[book]
authors = ["Jan Gaura", "Jakub Beránek", "Daniel Trnka"]
language = "cs"
multilingual = false
src = "src"
title = "Úvod do programování"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/geordi/upr-skripta"
default-theme = "rust"
preferred-dark-theme = "rust"
