name: Deploy

on:
  push:
    branches:
      - master

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                persist-credentials: false
            - name: Download mdBook
              run: |
                  wget -q "https://github.com/kobzol/mdBook/releases/download/release/mdbook"
                  chmod u+x mdbook
                  mkdir ~/bin
                  mv ./mdbook ~/bin/
                  echo "~/bin" >> $GITHUB_PATH

            - name: Cache mdbook-plantuml
              uses: actions/cache@v2
              with:
                path: |
                  ~/.cargo/bin/mdbook-plantuml
                  ~/.cargo/.crates.toml
                  ~/.cargo/.crates2.json
                key: ${{ runner.os }}-cache-plantuml-${{ github.run_id }}
                restore-keys: |
                  ${{ runner.os }}-cache-plantuml-

            - name: Install mdbook-plantuml
              run: cargo install mdbook-plantuml

            - name: Build
              run: mdbook build
              env:
                MDBOOK_OUTPUT__HTML__SITE_URL: /upr-skripta/

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: book
                CLEAN: true
